name: Makefile CI

on:
  push:
    branches: [ "main", "dev-build" ]
  pull_request:
    branches: [ "main", "dev-bulid" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build tools
      run: | 
        sudo apt update 
        sudo apt install -y gcc-arm-none-eabi gdb-arm-none-eabi
    - name: Build bootloader 
      run: |
        cd bootloader
        make -j
        cd ..
    - name: Build firmware
      run: |
        cd firmware
        make -j
        cd ..

    - name: Archive build files
      uses: actions/upload-artifact@v3
      with:
            name: 50x50_Bootloader.hex
            path: bootloader/build/50x50_Bootloader.hex
    